import Head from 'next/head';
import { About, Contact, Experience, Feedbacks, Hero, Navbar, Tech, Works, StarsCanvas } from '../components';
export default function Home() {
    return (
        <>
            <Head>
                <title>Portfolio | Danth</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="relative z-0 bg-primary">
                <div className="bg-hero-pattern bg-cover bg-center bg-no-repeat">
                    <Navbar />
                    <Hero />
                </div>
                <About />
                <Experience />
                <Tech />
                <Works />
                <Feedbacks />
                <div className="relative z-0">
                    <Contact />
                </div>
            </div>
        </>
    );
}
