import Head from 'next/head';
import { About, Contact, Experience, Feedbacks, Hero, Navbar, Tech, Works } from '../components';
import Tech1 from '../components/Tech1';
import dynamic from 'next/dynamic';
const Stars = dynamic(() => import('@/components/canvas/Stars'), { ssr: false });
export default function Home() {
    return (
        <>
            <Head>
                <title>Portfolio | Danth</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="relative z-0 bg-primary">
                <div className="bg-hero-pattern bg-cover bg-center bg-no-repeat">
                    <Navbar />
                    <Hero />
                </div>
                <About />
                <Experience />
                <div className="relative z-0">
                    <Tech1 />
                    <Stars />
                </div>

                <Works />

                <div className="relative z-0">
                    <Contact />
                    <Stars />
                </div>
            </div>
        </>
    );
}
